### ISSUE TITLE
perfomance optimizations

### ISSUE THREAD

**Issue by jogibear9988** [adobe/css-tools#99]
as we are getting more at-rules, maybe we should check, if it would be better to check with startsWith, before we use all the regexes.
and also do we look if first char is a @?

for me perfomance is not so relevant, but as you already did some meassurement, maybe for you is?

**Comment by jogibear9988** [comment]
and also, would it be better to create regexp instances and reuse them?

**Comment by holblin** [comment]
I think when I tried to improve it last time I got some similar thinking and after a few experimentations, it wasn't better. I think I might have tried some `startWith` and so on. Though I might have missed some things also, regex is pretty optimized these days.

I'm not too much oriented for performances either. I improved them because I could and I'm not afraid of modifying regex. Also, it was a great way to promote a fork :-)
I totally agree that we might be able to improve performances and that would be amazing, though it's not a priority for me. If someone what to experiment without introducing regression 👍 Otherwise, I might not be able to look at it for multiple months.
